version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: birthday_reminder
      MYSQL_USER: br_user
      MYSQL_PASSWORD: br_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  server:
    build: ./server
    command: npm run dev
    volumes:
      - ./server:/usr/src/app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: br_user
      DB_PASSWORD: br_password
      DB_NAME: birthday_reminder
    depends_on:
      - db

volumes:
  db_data: