services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: birthday_reminder
      MYSQL_USER: br_user
      MYSQL_PASSWORD: br_password
    ports:
      - "3307:3306"  # Changed from 3306:3306 to 3307:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: